baseURL = 'https://accelerated-computing.com/'
languageCode = 'en-us'
title = 'Accelerated Computing'
# theme = 'ac-theme'

pluralizeListTitles = false

[outputs]
  home = ['HTML', 'RSS']

[Author]
  name = "Thomas O'Brien"

[menu]
[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 10
[[menu.main]]
  name = 'Blog'
  url = '/blog'
  weight = 20
[[menu.main]]
  name = 'About'
  url = '/about'
  weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min      = "0.112.0"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "hugo_stats.json"
    target = "assets/watching/hugo_stats.json"

[build]
  writeStats = true
  [[build.cachebusters]]
    source = "assets/watching/hugo_stats\\.json"
    target = "style\\.css"
  [[build.cachebusters]]
    source = "(postcss|tailwind)\\.config\\.js"
    target = "css"
  [[build.cachebusters]]
    source = "assets/.*\\.(js|ts|jsx|tsx)"
    target = "js"
  [[build.cachebusters]]
    source = "assets/.*\\.(.*)$"
    target = "$1"

[markup]
  [markup.highlight]
    noClasses = false